[project]
name = "mcp-deep-dive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.0",
    "openai>=1.101.0",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
]
